version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=mask
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
    ports:
      - 5432
