# Generated by Django 3.2.7 on 2021-09-09 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mask_api', '0003_purchasehistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='pharmacies',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasehistory', to='mask_api.user'),
        ),
    ]
